name: Auto Create CM PR

on:
  pull_request:
    branches:
      - dev-RM
    types: [closed]

  
jobs:
  auto-create:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # required to see full history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

      - name: Create Temp Branch from Feature Branch
        id: create-temp
        run: |
          FEATURE_BRANCH=${{ github.event.pull_request.head.ref }}
          TEMP_BRANCH=temp-$FEATURE_BRANCH
          git fetch origin
          git checkout $FEATURE_BRANCH
          git checkout -b $TEMP_BRANCH
          # Make sure there is at least 1 commit; temp branch has changes
          git push origin $TEMP_BRANCH
          echo "Temp branch created: $TEMP_BRANCH"

      - name: Create PR to dev-CM
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.TEMP_BRANCH }}      # temp branch pushed
          base: dev-CM                        # base branch CM
          title: "Synchronizing RM Changes to CM"
          body: |
            Auto-created PR from temp branch ${{ env.TEMP_BRANCH }} to dev-CM
            Please resolve conflicts if any, then merge.